[package]
name = "lexicon"
version = "0.1.0"
authors = ["Yasuhiro Asaka <yasuhiro.asaka@grauwoelfchen.net>"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
clippy = { version = "^0.0.193" }
